# Generated by Django 5.1.6 on 2026-09-05 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('credentials', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='instructor_covers/')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
