# Generated by Django 5.1.6 on 2026-09-07 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructorprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='admin_quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='instructor_intro_videos/'),
        ),
    ]
