# Generated by Django 5.1.6 on 2026-09-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-access_granted_at',)},
        ),
    ]
