# Generated by Django 5.1.6 on 2026-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_theme',
            field=models.CharField(choices=[('teal', 'Teal & Amber'), ('blue', 'Blue & Rose'), ('purple', 'Purple & Gold'), ('mono', 'Monochrome & Amber')], default='teal', max_length=20),
        ),
    ]
