# Generated by Django 5.1.6 on 2026-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color_theme',
            field=models.CharField(choices=[('teal', 'Teal & Amber'), ('blue', 'Blue & Rose'), ('purple', 'Purple & Gold'), ('mono', 'Monochrome & Amber'), ('green', 'Green & Amber'), ('red', 'Red & Gold'), ('orange', 'Orange & Blue')], default='teal', max_length=20),
        ),
    ]
