# Generated by Django 5.1.6 on 2026-09-07 10:28, hand-edited to preserve
# existing users' color_theme choice as its equivalent hex pair instead of
# silently resetting everyone to the new default.

import django.core.validators
from django.db import migrations, models

OLD_PRESET_HEX = {
    "teal": ("#157e6c", "#f98307"),
    "blue": ("#2563eb", "#db2777"),
    "purple": ("#7c3aed", "#ca8a04"),
    "mono": ("#475569", "#f98307"),
    "green": ("#16a34a", "#f98307"),
    "red": ("#dc2626", "#ca8a04"),
    "orange": ("#ea580c", "#2563eb"),
}


def migrate_color_theme_to_hex(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for old_value, (primary, accent) in OLD_PRESET_HEX.items():
        User.objects.filter(color_theme=old_value).update(primary_color=primary, accent_color=accent)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent_color',
            field=models.CharField(default='#f98307', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #157e6c).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_color',
            field=models.CharField(default='#157e6c', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #157e6c).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.RunPython(migrate_color_theme_to_hex, noop_reverse),
        migrations.RemoveField(
            model_name='user',
            name='color_theme',
        ),
    ]
