# Generated by Django 5.1.6 on 2026-09-07 10:42, hand-edited to backfill
# header_color/nav_color from each user's existing primary_color instead
# of leaving everyone on the new field's flat default — someone who'd
# already customized their primary color would otherwise see a jarring
# mismatch the moment header/nav diverge from it.

import django.core.validators
from django.db import migrations, models


def backfill_from_primary(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.update(header_color=models.F("primary_color"), nav_color=models.F("primary_color"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_color_theme_user_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_color',
            field=models.CharField(default='#157e6c', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #157e6c).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='nav_color',
            field=models.CharField(default='#157e6c', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #157e6c).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.RunPython(backfill_from_primary, noop_reverse),
    ]
