# Generated by Django 5.1.6 on 2026-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='room_slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
